services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"  
    volumes:
      - /Users/thirumal/git/oauth-authorization-server/logs:/logs  # host:container
      - ./alloy-config.alloy:/etc/alloy/alloy-config.alloy:ro
    command: run /etc/alloy/alloy-config.alloy
    networks:
      - grafana-net

networks:
  grafana-net:
    driver: bridge

