# Use root/example as user/password credentials

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    # (this is just an example, not intended to be a production configuration)
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mysql-network
networks:
  mysql-network:
    driver: bridge